code: bmm
name: 'BMad Method Agile-AI Driven-Development'
description: 'AI-driven agile development framework'

project_name: '1st Class Chimney & Air Duct'
user_name: 'Yaron'
user_skill_level: 'expert'
communication_language: 'en'
document_output_language: 'en'
output_folder: '_bmad-output'
planning_artifacts: '_bmad-output/planning-artifacts'
implementation_artifacts: '_bmad-output/implementation-artifacts'
project_knowledge: 'docs'
date: '2026-02-20'
